In [1]:
import pandas as pd
import numpy as np
import tensorflow
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [2]:
'''data columns are: Index(['Day', 'Month', 'Year', 'States/UTs', 'Rice', 'Wheat', 'Atta (Wheat)',
       'Gram Dal', 'Tur/Arhar Dal', 'Urad Dal', 'Moong Dal', 'Masoor Dal',
       'Sugar', 'Milk @', 'Groundnut Oil (Packed)', 'Mustard Oil (Packed)',
       'Vanaspati (Packed)', 'Soya Oil (Packed)', 'Sunflower Oil (Packed)',
       'Palm Oil (Packed)', 'Gur', 'Tea Loose', 'Salt Pack (Iodised)',
       'Potato', 'Onion', 'Tomato'],
      dtype='object')'''

"data columns are: Index(['Day', 'Month', 'Year', 'States/UTs', 'Rice', 'Wheat', 'Atta (Wheat)',\n       'Gram Dal', 'Tur/Arhar Dal', 'Urad Dal', 'Moong Dal', 'Masoor Dal',\n       'Sugar', 'Milk @', 'Groundnut Oil (Packed)', 'Mustard Oil (Packed)',\n       'Vanaspati (Packed)', 'Soya Oil (Packed)', 'Sunflower Oil (Packed)',\n       'Palm Oil (Packed)', 'Gur', 'Tea Loose', 'Salt Pack (Iodised)',\n       'Potato', 'Onion', 'Tomato'],\n      dtype='object')"

In [3]:
# Load the data from the CSV file
df = pd.read_csv(r"data\cleansing\filled\data_r_mean_filled.csv")

In [4]:
print(df.shape)

(89280, 26)


In [5]:
df = df[(df["Year"] >=2023)]
print(df.shape)

(19700, 26)


In [6]:
# Convert date columns to a datetime object
df['Date'] = pd.to_datetime(df[['Day', 'Month', 'Year']])
df.set_index('Date', inplace=True)

In [7]:
# Select the crops for prediction
crops = ["Rice", "Wheat", "Atta (Wheat)", "Gram Dal", "Tur/Arhar Dal", "Urad Dal", "Moong Dal", "Masoor Dal", "Sugar", "Milk @", "Groundnut Oil (Packed)", "Mustard Oil (Packed)", "Vanaspati (Packed)", "Soya Oil (Packed)", "Sunflower Oil (Packed)", "Palm Oil (Packed)", "Gur", "Tea Loose", "Salt Pack (Iodised)", "Potato", "Onion", "Tomato"]

In [8]:
print(len(crops))

22


In [9]:
# Create a dictionary to store the last known data for each state
last_known_data = {}
for state in df['States/UTs'].unique():
    last_known_data[state] = df[df['States/UTs'] == state].iloc[-1][crops].values

In [10]:
# Prepare data for LSTM
data = df[crops].values
print(data.shape)

(19700, 22)


In [11]:
# Scale the data to be between 0 and 1
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(data)

In [12]:
# Split the data into training and testing sets
train_data, test_data = train_test_split(scaled_data, test_size=0.2)
print(train_data)

[[0.42613636 0.70580645 0.5        ... 0.38836066 0.59710526 0.3222439 ]
 [0.52659091 0.38709677 0.28166667 ... 0.22131148 0.30039474 0.18941463]
 [0.29159091 0.3283871  0.19047619 ... 0.05868852 0.08447368 0.01990244]
 ...
 [0.38636364 0.35483871 0.30952381 ... 0.37704918 0.47368421 0.37560976]
 [0.5        0.43346774 0.42857143 ... 0.24590164 0.18421053 0.25365854]
 [0.64318182 0.63548387 0.40952381 ... 0.29344262 0.61578947 0.10390244]]


In [13]:
# Create the function to create the dataset
def create_dataset(dataset, look_back=1):
    X, Y = [], []
    for i in range(len(dataset)-look_back-1):
        a = dataset[i:(i+look_back), :]
        X.append(a)
        Y.append(dataset[i + look_back, :])
    return np.array(X), np.array(Y)

In [14]:
# Set look_back period (number of previous days to consider)
look_back = 7
X_train, Y_train = create_dataset(train_data, look_back)
X_test, Y_test = create_dataset(test_data, look_back)

In [15]:
# Reshape input to be [samples, time steps, features]
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], X_train.shape[2]))
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], X_test.shape[2]))

In [16]:
# Create and fit the LSTM network
model = Sequential()
model.add(LSTM(units=50, return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(LSTM(units=50))
model.add(Dense(X_train.shape[2]))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(X_train, Y_train, epochs=100, batch_size=1, verbose=2)


Epoch 1/100


c:\Users\krish\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


15752/15752 - 36s - 2ms/step - loss: 0.0255
Epoch 2/100
15752/15752 - 33s - 2ms/step - loss: 0.0251
Epoch 3/100
15752/15752 - 33s - 2ms/step - loss: 0.0250
Epoch 4/100
15752/15752 - 33s - 2ms/step - loss: 0.0250
Epoch 5/100
15752/15752 - 33s - 2ms/step - loss: 0.0250
Epoch 6/100
15752/15752 - 35s - 2ms/step - loss: 0.0250
Epoch 7/100
15752/15752 - 35s - 2ms/step - loss: 0.0249
Epoch 8/100
15752/15752 - 36s - 2ms/step - loss: 0.0249
Epoch 9/100
15752/15752 - 34s - 2ms/step - loss: 0.0249
Epoch 10/100
15752/15752 - 33s - 2ms/step - loss: 0.0249
Epoch 11/100
15752/15752 - 33s - 2ms/step - loss: 0.0249
Epoch 12/100
15752/15752 - 34s - 2ms/step - loss: 0.0249
Epoch 13/100
15752/15752 - 33s - 2ms/step - loss: 0.0249
Epoch 14/100
15752/15752 - 32s - 2ms/step - loss: 0.0249
Epoch 15/100
15752/15752 - 33s - 2ms/step - loss: 0.0249
Epoch 16/100
15752/15752 - 33s - 2ms/step - loss: 0.0249
Epoch 17/100
15752/15752 - 37s - 2ms/step - loss: 0.0249
Epoch 18/100
15752/15752 - 36s - 2ms/step - loss: 0.

KeyboardInterrupt: 

In [17]:
# save the model
model.save('model01.keras')

In [ ]:
# Save the scaler
import joblib
joblib.dump(scaler, 'scaler.pkl')

In [18]:
# Scale the data to be between 0 and 1
#scaler = MinMaxScaler(feature_range=(0, 1))
last_week_data = df[crops].iloc[-7:].values 
scaled_last_week = scaler.transform(last_week_data) 
reshaped_last_week = np.reshape(scaled_last_week, (1, look_back, len(crops))) 

In [ ]:
# Predict
prediction_scaled = model.predict(reshaped_last_week)
prediction = scaler.inverse_transform(prediction_scaled)

In [20]:
# Create DataFrame for 6/9/2024 predictions
predictions_6_9_2024 = pd.DataFrame(data=prediction, columns=crops)

In [ ]:
# Predict for all states using the last known data
for state, state_data in last_known_data.items():
    scaled_state_data = scaler.transform(state_data.reshape(1,-1))
    reshaped_state_data = np.reshape(scaled_state_data, (1, 1, len(crops)))

    state_prediction_scaled = model.predict(reshaped_state_data)
    state_prediction = scaler.inverse_transform(state_prediction_scaled)

    predictions_6_9_2024.loc[state] = state_prediction[0]

In [ ]:
# Display the predictions
print(predictions_6_9_2024)

# --------------------------------------------------

In [ ]:
# Predict for all states using a rolling window of past data
predictions_by_state = {}  # Dictionary to store predictions for each state

In [ ]:
for state in df['States/UTs'].unique():
    state_data = df[df['States/UTs'] == state][crops].iloc[-look_back:].values # Last 'look_back' days of data
    scaled_state_data = scaler.transform(state_data)
    reshaped_state_data = np.reshape(scaled_state_data, (1, look_back, len(crops)))

    state_prediction_scaled = model.predict(reshaped_state_data)
    state_prediction = scaler.inverse_transform(state_prediction_scaled)
    predictions_by_state[state] = state_prediction[0] # Store prediction for the state


In [ ]:
predictions_df = pd.DataFrame(predictions_by_state).T # Convert to DataFrame for better display
predictions_df.columns = crops # Add column names
print(predictions_df)